### ISSUE TITLE
help

### ISSUE THREAD

**Issue by keyofcg** [rayryeng/laplacianBlend#3]
i have run your code ,but my mask is irregular ,and the laplacian stitching can not  get the second image,only the first image,could you tell me why
![image](https://user-images.githubusercontent.com/9145147/35085905-870c7c7c-fc65-11e7-8afb-bdfa836b786a.png)
![image](https://user-images.githubusercontent.com/9145147/35085918-8f3ed700-fc65-11e7-9926-9affa8d74ceb.png)
![image](https://user-images.githubusercontent.com/9145147/35085924-9623e222-fc65-11e7-8a86-ee0231b24961.png)

**Comment by rayryeng** [comment]
Your mask doesn't span any common areas of the second image. Only the first image and the mask area defined seems to be only for the borders. You have to properly define your mask so it spans the valid pixels for the second image.

**Comment by keyofcg** [comment]
thank you ,i have fixed the problem ,but i found there are little diffirentce betweent the Laplacian Blending and simply add two image. how to solve that？
![image](https://user-images.githubusercontent.com/9145147/35130652-f964a6b8-fcfc-11e7-8526-a404a700cdc7.png)
![image](https://user-images.githubusercontent.com/9145147/35130657-02d7768a-fcfd-11e7-9b75-b9a29392c224.png)
![image](https://user-images.githubusercontent.com/9145147/35130659-0877f664-fcfd-11e7-9c16-1574cfed816c.png)
![image](https://user-images.githubusercontent.com/9145147/35130666-0bec3364-fcfd-11e7-8a76-71753640b5d2.png)
![image](https://user-images.githubusercontent.com/9145147/35130669-127d646e-fcfd-11e7-894c-1db7aa2a1680.png)

**Comment by rayryeng** [comment]
The method is only good for blending the image borders. You'll want a more sophisticated method, such as multiband blending.

**Comment by keyofcg** [comment]
but i test this two images  but i ,can not get the same quality of your  datasets
